// src/services/serviceApi.js

export async function fetchServices() {
  return [
    {
      id: 1,
      name: "Laundry Service",
      vendorName: "CleanWave Laundry",
      rating: 4.5,
      reviews: 34,
      price: "$5 per kg",
      category: "Laundry",
      description: "Professional laundry service with quick turnaround and quality care for your clothes.",
    },
    {
      id: 2,
      name: "Printing Service",
      vendorName: "SwiftPrint",
      rating: 4.2,
      reviews: 17,
      price: "$0.20 per page",
      category: "Printing",
      description: "High-quality printing services for documents, assignments, and posters.",
    },
    {
      id: 3,
      name: "Tutoring",
      vendorName: "TutorHub",
      rating: 4.8,
      reviews: 41,
      price: "$10/hr",
      category: "Tutoring",
      description: "Expert tutoring services across various subjects to help you excel academically.",
    },
    {
      id: 4,
      name: "Campus Cafe",
      vendorName: "Brew & Study",
      rating: 4.6,
      reviews: 89,
      price: "$3-8 per item",
      category: "Food & Beverage",
      description: "Fresh coffee, snacks, and meals perfect for study breaks and quick bites.",
    },
    {
      id: 5,
      name: "Bike Rental",
      vendorName: "Campus Cycles",
      rating: 4.3,
      reviews: 52,
      price: "$2/hr",
      category: "Transportation",
      description: "Affordable bike rentals for getting around campus quickly and sustainably.",
    },
    {
      id: 6,
      name: "Tech Support",
      vendorName: "IT Solutions",
      rating: 4.7,
      reviews: 28,
      price: "$15/hr",
      category: "Technology",
      description: "Computer repair, software installation, and technical assistance for students.",
    },
    {
      id: 7,
      name: "Book Binding",
      vendorName: "Academic Binders",
      rating: 4.4,
      reviews: 33,
      price: "$5-15 per book",
      category: "Academic Services",
      description: "Professional binding services for theses, dissertations, and course materials.",
    },
    {
      id: 8,
      name: "Photography",
      vendorName: "Campus Capture",
      rating: 4.9,
      reviews: 67,
      price: "$25-100 per session",
      category: "Creative Services",
      description: "Professional photography for events, portraits, and campus activities.",
    },
    {
      id: 9,
      name: "Car Wash",
      vendorName: "Sparkle Auto",
      rating: 4.1,
      reviews: 45,
      price: "$15 per car",
      category: "Automotive",
      description: "Convenient car washing services with eco-friendly products and quick service.",
    },
  ];
}

export async function fetchMockBookings() {
  return [
    {
      id: 1,
      service: "Laundry Service",
      vendor: "CleanWave Laundry",
      date: "2025-02-03",
      status: "confirmed",
    },
    {
      id: 2,
      service: "Printing Service",
      vendor: "SwiftPrint",
      date: "2025-02-05",
      status: "pending",
    },
    {
      id: 3,
      service: "Tutoring Session",
      vendor: "TutorHub",
      date: "2025-02-07",
      status: "completed",
    },
  ];
}
